package com.officeutq.springtest.domain.mybatis;

import java.util.Date;

public class IndexList {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column index_list.screen_id
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	private String screenId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column index_list.index_title
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	private String indexTitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column index_list.index_exp
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	private String indexExp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column index_list.index_date
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	private Date indexDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column index_list.index_memo
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	private String indexMemo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column index_list.screen_id
	 * @return  the value of index_list.screen_id
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	public String getScreenId() {
		return screenId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column index_list.screen_id
	 * @param screenId  the value for index_list.screen_id
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	public void setScreenId(String screenId) {
		this.screenId = screenId == null ? null : screenId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column index_list.index_title
	 * @return  the value of index_list.index_title
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	public String getIndexTitle() {
		return indexTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column index_list.index_title
	 * @param indexTitle  the value for index_list.index_title
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	public void setIndexTitle(String indexTitle) {
		this.indexTitle = indexTitle == null ? null : indexTitle.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column index_list.index_exp
	 * @return  the value of index_list.index_exp
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	public String getIndexExp() {
		return indexExp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column index_list.index_exp
	 * @param indexExp  the value for index_list.index_exp
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	public void setIndexExp(String indexExp) {
		this.indexExp = indexExp == null ? null : indexExp.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column index_list.index_date
	 * @return  the value of index_list.index_date
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	public Date getIndexDate() {
		return indexDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column index_list.index_date
	 * @param indexDate  the value for index_list.index_date
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	public void setIndexDate(Date indexDate) {
		this.indexDate = indexDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column index_list.index_memo
	 * @return  the value of index_list.index_memo
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	public String getIndexMemo() {
		return indexMemo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column index_list.index_memo
	 * @param indexMemo  the value for index_list.index_memo
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	public void setIndexMemo(String indexMemo) {
		this.indexMemo = indexMemo == null ? null : indexMemo.trim();
	}
}