package com.officeutq.springtest.domain.mybatis;

public class Test003FruitsPartner {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test003_fruits_partner.partner_id
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	private String partnerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test003_fruits_partner.partner_name
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	private String partnerName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test003_fruits_partner.partner_products
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	private Object partnerProducts;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test003_fruits_partner.partner_id
	 * @return  the value of test003_fruits_partner.partner_id
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	public String getPartnerId() {
		return partnerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test003_fruits_partner.partner_id
	 * @param partnerId  the value for test003_fruits_partner.partner_id
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	public void setPartnerId(String partnerId) {
		this.partnerId = partnerId == null ? null : partnerId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test003_fruits_partner.partner_name
	 * @return  the value of test003_fruits_partner.partner_name
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	public String getPartnerName() {
		return partnerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test003_fruits_partner.partner_name
	 * @param partnerName  the value for test003_fruits_partner.partner_name
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	public void setPartnerName(String partnerName) {
		this.partnerName = partnerName == null ? null : partnerName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test003_fruits_partner.partner_products
	 * @return  the value of test003_fruits_partner.partner_products
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	public Object getPartnerProducts() {
		return partnerProducts;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test003_fruits_partner.partner_products
	 * @param partnerProducts  the value for test003_fruits_partner.partner_products
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	public void setPartnerProducts(Object partnerProducts) {
		this.partnerProducts = partnerProducts;
	}
}