package com.officeutq.springtest.domain.mybatis;

import java.util.Date;

public class Test003FruitsTransaction {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test003_fruits_transaction.sequence_id
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	private Integer sequenceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test003_fruits_transaction.fruits_id
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	private String fruitsId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test003_fruits_transaction.transaction_count
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	private Integer transactionCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test003_fruits_transaction.transaction_date
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	private Date transactionDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test003_fruits_transaction.partner_id
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	private String partnerId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test003_fruits_transaction.sequence_id
	 * @return  the value of test003_fruits_transaction.sequence_id
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	public Integer getSequenceId() {
		return sequenceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test003_fruits_transaction.sequence_id
	 * @param sequenceId  the value for test003_fruits_transaction.sequence_id
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	public void setSequenceId(Integer sequenceId) {
		this.sequenceId = sequenceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test003_fruits_transaction.fruits_id
	 * @return  the value of test003_fruits_transaction.fruits_id
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	public String getFruitsId() {
		return fruitsId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test003_fruits_transaction.fruits_id
	 * @param fruitsId  the value for test003_fruits_transaction.fruits_id
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	public void setFruitsId(String fruitsId) {
		this.fruitsId = fruitsId == null ? null : fruitsId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test003_fruits_transaction.transaction_count
	 * @return  the value of test003_fruits_transaction.transaction_count
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	public Integer getTransactionCount() {
		return transactionCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test003_fruits_transaction.transaction_count
	 * @param transactionCount  the value for test003_fruits_transaction.transaction_count
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	public void setTransactionCount(Integer transactionCount) {
		this.transactionCount = transactionCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test003_fruits_transaction.transaction_date
	 * @return  the value of test003_fruits_transaction.transaction_date
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	public Date getTransactionDate() {
		return transactionDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test003_fruits_transaction.transaction_date
	 * @param transactionDate  the value for test003_fruits_transaction.transaction_date
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	public void setTransactionDate(Date transactionDate) {
		this.transactionDate = transactionDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test003_fruits_transaction.partner_id
	 * @return  the value of test003_fruits_transaction.partner_id
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	public String getPartnerId() {
		return partnerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test003_fruits_transaction.partner_id
	 * @param partnerId  the value for test003_fruits_transaction.partner_id
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	public void setPartnerId(String partnerId) {
		this.partnerId = partnerId == null ? null : partnerId.trim();
	}
}