package com.officeutq.springtest.mapper.mybatis;

import com.officeutq.springtest.domain.mybatis.IndexList;
import com.officeutq.springtest.domain.mybatis.IndexListExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IndexListMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table index_list
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	long countByExample(IndexListExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table index_list
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	int deleteByExample(IndexListExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table index_list
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	int deleteByPrimaryKey(String screenId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table index_list
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	int insert(IndexList record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table index_list
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	int insertSelective(IndexList record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table index_list
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	List<IndexList> selectByExample(IndexListExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table index_list
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	IndexList selectByPrimaryKey(String screenId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table index_list
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	int updateByExampleSelective(@Param("record") IndexList record, @Param("example") IndexListExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table index_list
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	int updateByExample(@Param("record") IndexList record, @Param("example") IndexListExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table index_list
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	int updateByPrimaryKeySelective(IndexList record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table index_list
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	int updateByPrimaryKey(IndexList record);
}