package com.officeutq.springtest.mapper.mybatis;

import com.officeutq.springtest.domain.mybatis.Test003FruitsPartner;
import com.officeutq.springtest.domain.mybatis.Test003FruitsPartnerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Test003FruitsPartnerMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test003_fruits_partner
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	long countByExample(Test003FruitsPartnerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test003_fruits_partner
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	int deleteByExample(Test003FruitsPartnerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test003_fruits_partner
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	int deleteByPrimaryKey(String partnerId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test003_fruits_partner
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	int insert(Test003FruitsPartner record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test003_fruits_partner
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	int insertSelective(Test003FruitsPartner record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test003_fruits_partner
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	List<Test003FruitsPartner> selectByExample(Test003FruitsPartnerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test003_fruits_partner
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	Test003FruitsPartner selectByPrimaryKey(String partnerId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test003_fruits_partner
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	int updateByExampleSelective(@Param("record") Test003FruitsPartner record,
			@Param("example") Test003FruitsPartnerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test003_fruits_partner
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	int updateByExample(@Param("record") Test003FruitsPartner record,
			@Param("example") Test003FruitsPartnerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test003_fruits_partner
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	int updateByPrimaryKeySelective(Test003FruitsPartner record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test003_fruits_partner
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	int updateByPrimaryKey(Test003FruitsPartner record);
}