package com.officeutq.springtest.mapper.mybatis;

import com.officeutq.springtest.domain.mybatis.Test003FruitsTransaction;
import com.officeutq.springtest.domain.mybatis.Test003FruitsTransactionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Test003FruitsTransactionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test003_fruits_transaction
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	long countByExample(Test003FruitsTransactionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test003_fruits_transaction
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	int deleteByExample(Test003FruitsTransactionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test003_fruits_transaction
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	int deleteByPrimaryKey(Integer sequenceId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test003_fruits_transaction
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	int insert(Test003FruitsTransaction record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test003_fruits_transaction
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	int insertSelective(Test003FruitsTransaction record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test003_fruits_transaction
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	List<Test003FruitsTransaction> selectByExample(Test003FruitsTransactionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test003_fruits_transaction
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	Test003FruitsTransaction selectByPrimaryKey(Integer sequenceId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test003_fruits_transaction
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	int updateByExampleSelective(@Param("record") Test003FruitsTransaction record,
			@Param("example") Test003FruitsTransactionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test003_fruits_transaction
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	int updateByExample(@Param("record") Test003FruitsTransaction record,
			@Param("example") Test003FruitsTransactionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test003_fruits_transaction
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	int updateByPrimaryKeySelective(Test003FruitsTransaction record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test003_fruits_transaction
	 * @mbg.generated  Fri Apr 16 22:12:27 JST 2021
	 */
	int updateByPrimaryKey(Test003FruitsTransaction record);
}